# Generated by Django 3.0.8 on 2020-10-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=4, unique=True)),
                ('exchange_rate', models.DecimalField(decimal_places=10, max_digits=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
